services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=DonoDash_Database
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
    restart: always

volumes:
  config-volume: